trigger:
  branches:
    include:
      - main
stages:
- stage:

  jobs:
  - job: 

    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: "latest"

    - task: TerraformTask@5
      displayName: "Terraform Init"
      inputs:
        provider: "azurerm"
        command: "init"
        backendServiceArm: "infraconnetion"
        backendAzureRmResourceGroupName: "rg-backend"
        backendAzureRmStorageAccountName: "backeend151988vk"
        backendAzureRmContainerName: "statefile"
        backendAzureRmKey: "statefile1.tfstate"
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'plan'
        environmentServiceNameAzureRM: 'infraconnetion'
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'apply'
        environmentServiceNameAzureRM: 'infraconnetion'

   



           

